# Generated by Django 4.2.11 on 2025-05-12 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="cioc",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="country",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="api.country",
            ),
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="country",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postal_codes",
                to="api.country",
            ),
        ),
    ]
