# Generated by Django 4.2.11 on 2025-05-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_country_cioc_alter_car_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ginivalue",
            name="gini",
        ),
        migrations.RemoveField(
            model_name="nativenamevalue",
            name="nativeName",
        ),
        migrations.RemoveField(
            model_name="translationvalue",
            name="translation",
        ),
        migrations.RenameField(
            model_name="demonym",
            old_name="demonym",
            new_name="f",
        ),
        migrations.RenameField(
            model_name="nativename",
            old_name="type",
            new_name="name",
        ),
        migrations.AddField(
            model_name="demonym",
            name="m",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="demonym",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gini",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nativename",
            name="common",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="nativename",
            name="official",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="translation",
            name="common",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="translation",
            name="official",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="DenomynValue",
        ),
        migrations.DeleteModel(
            name="GiniValue",
        ),
        migrations.DeleteModel(
            name="nativeNameValue",
        ),
        migrations.DeleteModel(
            name="TranslationValue",
        ),
    ]
