# Generated by Django 4.2.11 on 2025-05-12 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_ginivalue_gini_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="api.country",
            ),
        ),
        migrations.AlterField(
            model_name="postalcode",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postal_codes",
                to="api.country",
            ),
        ),
    ]
