# Generated by Django 4.2.11 on 2025-05-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_car_country_alter_postalcode_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coatofarms",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coat_of_arms",
                to="api.country",
            ),
        ),
        migrations.AlterField(
            model_name="flag",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flag",
                to="api.country",
            ),
        ),
    ]
