# Generated by Django 4.2.11 on 2025-05-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_coatofarms_country_alter_flag_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capitalinfo",
            name="latlng",
        ),
        migrations.AddField(
            model_name="capitalinfo",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalinfo",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
